server:
  port: 8080

logging:
  level:
    root: DEBUG
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG
    org.springframework.cloud.gateway: INFO
#    org.springframework.boot.autoconfigure: DEBUG

provider:
  clientId: 601704593845-8nbsaqf58sk03plpd6cqd5snskc2v6du.apps.googleusercontent.com
  clientSecret: zagh_7IO13dNJwNVir24iL3D
  accessTokenUri: https://oauth2.googleapis.com/token
  userAuthorizationUri: https://accounts.google.com/o/oauth2/auth
  issuer: https://accounts.google.com
  jwkUrl: https://www.googleapis.com/oauth2/v2/certs
  scope: openid,email,profile
client:
  registrationId: login-client
  authorizationUri: /oauth2/authorization/login-client
  redirectUri: /login/oauth2/code/login-client
  redirectUriTemplate: "{baseUrl}/login/oauth2/code/{registrationId}"

spring:
  autoconfigure:
  thymeleaf:
    cache: false
